#!/usr/bin/env python3
# gen_music_data.py  —  parse mp3_online.csv → js/music_data.js

import csv, json, re, os

BASE_URL = "https://hylst.fr/hml/"
CSV_PATH = "mp3_online.csv"
OUT_PATH = os.path.join("js", "music_data.js")

def seconds_to_mmss(secs):
    try:
        s = int(secs)
        return f"{s // 60}:{s % 60:02d}"
    except Exception:
        return ""

tracks = []
with open(CSV_PATH, newline='', encoding='utf-8-sig') as f:
    reader = csv.DictReader(f, delimiter=';')
    for row in reader:
        filename = (row.get('Filename') or '').strip()
        if not filename or not filename.endswith('.mp3'):
            continue

        # Build safe slug (filename without extension)
        slug = filename.replace('.mp3', '')
        jpg_name = slug + '.jpg'

        title = (row.get('Title') or slug.replace('_', ' ').title()).strip()
        artist = (row.get('Artist') or 'Hylst').strip()
        genre = (row.get('Genre') or '').strip()
        year = (row.get('Year') or '').strip()
        mood = (row.get('Mood') or '').strip()
        keywords = (row.get('Keywords') or '').strip()
        bpm = (row.get('BPM') or '').strip()
        duration_raw = (row.get('AudioLength') or '').strip()
        duration = seconds_to_mmss(duration_raw)
        usage = (row.get('Usage') or '').strip()

        # Clean keywords — keep first 6 comma-separated
        kw_list = [k.strip() for k in keywords.split(',') if k.strip()][:6]
        tags = kw_list

        tracks.append({
            "id": slug,
            "title": title,
            "artist": artist,
            "genre": genre,
            "year": year,
            "mood": mood,
            "tags": tags,
            "bpm": bpm,
            "duration": duration,
            "usage": usage,
            "src": BASE_URL + filename,
            "cover": BASE_URL + jpg_name,
        })

# Sort alphabetically by title
tracks.sort(key=lambda t: t['title'].lower())

js_content = f"""// js/music_data.js  —  Auto-generated by gen_music_data.py — DO NOT EDIT MANUALLY
// {len(tracks)} tracks  ·  Source: https://hylst.fr/hml/
const MUSIC_LIBRARY = {json.dumps(tracks, ensure_ascii=False, indent=2)};
"""

with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"✅ Generated {OUT_PATH} with {len(tracks)} tracks.")
