#!/usr/bin/env python3
# gen_music_data.py  —  parse mp3_online.csv → js/music_data.js

import csv, json, re, os

BASE_URL = "https://hylst.fr/hml/"
CSV_PATH = "mp3_online.csv"
TXT_PATH = "mp3_online.txt"
OUT_PATH = os.path.join("js", "music_data.js")

def seconds_to_mmss(secs):
    try:
        # Handle cases like "163" or "163.0"
        s = int(float(secs))
        return f"{s // 60}:{s % 60:02d}"
    except Exception:
        return ""

def load_available_files(txt_path):
    if not os.path.exists(txt_path):
        return set()
    with open(txt_path, 'r', encoding='utf-8') as f:
        return {line.strip() for line in f if line.strip().endswith('.mp3')}

available_mp3s = load_available_files(TXT_PATH)
print(f"Loaded {len(available_mp3s)} available MP3 files from {TXT_PATH}")

tracks = []
metadata_by_filename = {}

if os.path.exists(CSV_PATH):
    with open(CSV_PATH, newline='', encoding='utf-8-sig') as f:
        lines = f.readlines()
        # Filter out empty lines
        clean_lines = [l for l in lines if l.strip()]
        
        if clean_lines:
            reader = csv.DictReader(clean_lines, delimiter=';')
            for row in reader:
                filename = (row.get('Filename') or '').strip()
                if not filename:
                    continue
                metadata_by_filename[filename] = row

for filename in sorted(available_mp3s):
    row = metadata_by_filename.get(filename, {})
    
    # Build safe slug (filename without extension)
    slug = filename.replace('.mp3', '')
    jpg_name = slug + '.jpg'

    title = (row.get('Title') or slug.replace('_', ' ').title()).strip()
    artist = (row.get('Artist') or 'Hylst').strip()
    genre = (row.get('Genre') or '').strip()
    year = (row.get('Year') or '').strip()
    mood = (row.get('Mood') or '').strip()
    keywords = (row.get('Keywords') or '').strip()
    bpm = (row.get('BPM') or '').strip()
    duration_raw = (row.get('AudioLength') or '').strip()
    duration = seconds_to_mmss(duration_raw)
    usage = (row.get('Usage') or '').strip()

    # Clean keywords — keep first 6 comma-separated
    kw_list = [k.strip() for k in keywords.split(',') if k.strip()][:6]
    tags = kw_list

    tracks.append({
        "id": slug,
        "title": title,
        "artist": artist,
        "genre": genre,
        "year": year,
        "mood": mood,
        "tags": tags,
        "bpm": bpm,
        "duration": duration,
        "usage": usage,
        "src": BASE_URL + filename,
        "cover": BASE_URL + jpg_name,
    })

# Sort alphabetically by title
tracks.sort(key=lambda t: t['title'].lower())

js_content = f"""// js/music_data.js  —  Auto-generated by gen_music_data.py — DO NOT EDIT MANUALLY
// {len(tracks)} tracks  ·  Source: {BASE_URL}
export const MUSIC_LIBRARY = {json.dumps(tracks, ensure_ascii=False, indent=2)};
"""

with open(OUT_PATH, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"✅ Generated {OUT_PATH} with {len(tracks)} tracks.")
